### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jasonbraganza** [pedro-augusto-santana/nemo_create_new_folder_with_selection#3]
Dear Pedro, 

I could not find you on the web anywhere, so decided to create an issue here :)

Just to say thank you so much for this little action of yours.

I have been a Mac user for the past 20 years and have recently switched to Mint. (about a year)

And this is one feature of osx that i sorely missed on Mint, until I found this today.

Thank you so, so, so much! :)

**Comment by pedro-augusto-santana** [comment]
Hey @jasonbraganza! Thank you for your support, I'm really glad I helped you felling more comfortable using Linux!
Have a nice time using it and hit me here if you need help with the code :)
