### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by RobertoQ** [pedro-augusto-santana/nemo_create_new_folder_with_selection#4]
Hi Pedro, I don't know if you're still working on this practical extension, but just in case I'll tell you about an option that for many of us who come from using nautilus and work with long series of files is very useful. When you select several files and carry out the action of copying them to a new folder, your default extension leaves the name of the new folder empty, however nautilus puts the title of the new folder with the letters that are common for all the selected files. This may seem like it doesn't make much sense, it is very useful when you are working with photos that have already been renamed with a common nomenclature, so you don't have to write the name of the folder. Is it an option that you would find interesting to integrate?
Greetings and thanks for developing such a necessary extension

![Create new folder with selected files](https://user-images.githubusercontent.com/3219518/180181497-2553577c-81f4-4c24-b2ff-62b1b57c3e92.png)

**Comment by pedro-augusto-santana** [comment]
Hello @RobertoQ! First of all thanks for the appreciation, I haven't used mint in a good 2 years, so I'm a little out on this and I don't have an installation at hand so I can't test for myself but I can help you implement it yourself, giving a look into the docs of zenity, it is possible to set an `--entry-text` parameter with a starting value for the input box

**Comment by pedro-augusto-santana** [comment]
If I'm recalling correctly, Mint has support for executing Python scripts in it's extensions, if that's still the case, you can use `commonprefix` from the standard library, using something like
```python
files = os.listdir(".")
prefix = os.path.commonprefix(files);
```
You could pass the selected items as parameters for the python file or use the selectors Linux Mint provides (i think)
And then with the common prefix you could set it using the `--entry-text` parameter on the zenity line
It is possible to do it with shell script as well, but is (a lot) more verbose and inintuitive

**Comment by RobertoQ** [comment]
Hello Pedro, thanks for your invaluable help.
I will speak with the developer of the school so that
 they follow your instructions and we can implement it.
 Again, thank you very much

Moito obrigado

Roberto Quintero

Escuela de Imagen y Sonido de Vigo

Galicia - Spain
